version: "3.9"
services:
    db:  # This service name will be also used as hostname for MONGODB_URI
      image: mongo:5.0.17
      env_file:
        - .env
      ports:
        - "27017:27017"
      volumes:
        - mongodb-data:/data/db
      restart: always

    backend:
        build:
            context: ./
        depends_on:
            - db
        env_file:
            - .env
        ports:
            - ${SHORTIFY_UVICORN_PORT}:${SHORTIFY_UVICORN_PORT}
        restart: always

volumes:
  mongodb-data:
