#!/bin/sh -e

export PREFIX=""

if [ -d ".venv" ] ; then
    export PREFIX=".venv/bin/"
fi
export SOURCE_FILES="shortify"

set -x

${PREFIX}isort --check --diff "$SOURCE_FILES"
${PREFIX}black --check --diff "$SOURCE_FILES"
${PREFIX}ruff "$SOURCE_FILES"
${PREFIX}mypy "$SOURCE_FILES"
