#!/bin/sh -e

POETRY_PATH="${HOME}/.local/share/pypoetry"
VENV=".venv"

if [ ! -d "$POETRY_PATH" ] ; then
    echo "Poetry not found, please first install poetry and then try again."
    exit 1
fi

# Configure poetry to install virtualenv in project directory
poetry config --local virtualenvs.in-project true

if [ ! -d "$VENV" ] ; then
    poetry env use python3
fi

poetry install -vv
