#!/bin/sh -e

export PREFIX=""

if [ -d '.venv' ] ; then
    export PREFIX=".venv/bin/"
fi
export SOURCE_FILES="shortify"

set -x

${PREFIX}ruff "$SOURCE_FILES" --fix
${PREFIX}isort "$SOURCE_FILES"
${PREFIX}black "$SOURCE_FILES"
