#!/bin/sh -e

export PREFIX=""

if [ -d '.venv' ] ; then
    export PREFIX=".venv/bin/"
fi
export SOURCE_FILES="shortify tests"

set -x

${PREFIX}autoflake --in-place --recursive "$SOURCE_FILES"
${PREFIX}isort --project=shortify "$SOURCE_FILES"
${PREFIX}black "$SOURCE_FILES"
