#!/bin/sh -e

export PREFIX=""

if [ -d ".venv" ] ; then
    export PREFIX=".venv/bin/"
fi

set -x

if [ -z "$GITHUB_ACTIONS" ]; then
    scripts/check
fi

# Use the `$@` to pass additional arguments to pytest.
# shellcheck disable=SC2068
${PREFIX}pytest $@
